### ISSUE TITLE
Level geometry

### ISSUE THREAD

**Issue by jacketeer** [smlu/Urgon#1]
Hi,

do you know how to get the "level geometry" out of the corresponding CND-files.

For example  the level-mesh (from 00_cyn.cnd)  that uses (among other textures) the "cyn_wall_rock_a" material file. 

---------------------------------
I'd like to get this:

Level geometry from 01_Canyonlands

![canyon](https://user-images.githubusercontent.com/56776406/68630472-c78bb600-04e7-11ea-99d8-ed68def07ca7.png)

06_Palawan Volcano

![palawan](https://user-images.githubusercontent.com/56776406/68630579-0a4d8e00-04e8-11ea-82ca-7f529f628049.png)

Those are screenshots from the program smith.exe

[http://www.jkhub.net/project/show.php?projid=829](url)

[https://smith.bah.wtf/](url)

---------------------------

Do you know how this could be accomplished?

Thanks

**Comment by smlu** [comment]
Hi, the develop branch of libim has implemented parsing of georesources including level geometry verticies, texture verticies, adjoins and surfaces.
You can find implementation in [cnd_section_georesource.cpp](https://github.com/smlu/ProjectMarduk/blob/fc81a32fe065e26bbf9674a91c60f1086b5453bb/src/libim/content/asset/world/impl/serialization/cnd/georesource/cnd_section_georesource.cpp#L31-L132). 
The [CND::ReadGeoresource](https://github.com/smlu/ProjectMarduk/blob/fc81a32fe065e26bbf9674a91c60f1086b5453bb/src/libim/content/asset/world/impl/serialization/cnd/cnd.h#L144) function can be used to extract level's [Georesource](https://github.com/smlu/ProjectMarduk/blob/fc81a32fe065e26bbf9674a91c60f1086b5453bb/src/libim/content/asset/world/georesource.h) structure.
e.g.: 
```
  auto is = InputFileStream("<path_to_level>.cnd");
  auto geores = CND::ReadGeoresource(is);
```

**Comment by smlu** [comment]
@jacketeer the develop branch of `libim` now implements code for parsing and writing sections [Things and Templates](https://github.com/smlu/ProjectMarduk/blob/0459c19f3ae8399024fbc688d086ea51318ae0dc/libraries/libim/content/asset/world/impl/serialization/cnd/cnd.h#L201-L209). Though `libim` is still missing the code for parsing 3D models, with this update you can now extract all objects (Things) from CND level including their initial position and orientation. 
There is one more section (`PVS`) left to be implemented after that you should be able to fully parse CND file. 

FYI,  I'm planning next to implement code for converting binary CND format to text based NDY level format. The `NDY` file format is slightly modified version of [JKL](https://www.massassi.net/jkspecs/jkl.htm) level file format (Star Wars Jedi Knight: Dark Forces II) and it can be edit in any text editor.

Additional ref: [https://www.massassi.net/jkspecs/](https://www.massassi.net/jkspecs/)

**Comment by smlu** [comment]
Small update:
**[cndtool](https://github.com/smlu/ProjectMarduk/releases/tag/v0.9.0)** can now extract and convert level geometry (vertices and UV vertices of level surfaces) to Wavefront .obj file format.
You can then use for example Blender to import created .obj file.

**Comment by jacketeer** [comment]
> 
> 
> Small update:
> **[cndtool](https://github.com/smlu/ProjectMarduk/releases/tag/v0.9.0)** can now extract and convert level geometry (vertices and UV vertices of level surfaces) to Wavefront .obj file format.
> You can then use for example Blender to import created .obj file.


Sounds great!

**Comment by smlu** [comment]
Update on ndy format:
The code base of `cndtool` was updated, and CND to NDY converting command was added. 
I'm still fixing some issues with cndtool, and unfortunately due to lack of time I haven't been able to release the new version yet.
If you are able to compile cndtool yourself you can already use `convert ndy` command and convert CND levels to NDY file format.
 
I've also made some docs for NDY file format, the docs can be found here: https://github.com/Jones3D-The-Infernal-Engine/Documentation/blob/main/ndy.md

Tutorial on how to use ndy files: https://github.com/Jones3D-The-Infernal-Engine/Documentation/blob/main/pre-mod.md
Note, the `conver ndy` command also extracts game assets from CND when converting so it's no need to extra extract those resources.

I'm also working on patch for OpenSith https://github.com/r1sc/OpenSith ,  to be able to load NDY file into Unity:
![image_2021-04-08_23-37-30](https://user-images.githubusercontent.com/4377556/124481255-60033800-dda8-11eb-8e5e-3a901e1aca9c.png)

![image_2021-04-24_00-57-42](https://user-images.githubusercontent.com/4377556/124480004-1cf49500-dda7-11eb-832c-30b076e0ab6c.png)

It's gonna probably take some time though for the patch before it's ready.

**Comment by smlu** [comment]
https://github.com/Jones3D-The-Infernal-Engine/Mods/tree/main/levels/sed

With this new level I think we can finally close this issue 🙂

**Comment by smlu** [comment]
Just referencing level editor for this game: https://github.com/smlu/SED
